# -*- coding: utf-8 -*-
"""Demo of Lung Cancer Detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vOR8mfl0brQp6H-4wiRFQOO7DItHru_Z
"""

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import tensorflow as tf
import numpy as np
from keras.models import load_model
from keras_preprocessing.image import ImageDataGenerator
from keras_preprocessing.image import img_to_array
from keras_preprocessing.image import load_img
model = load_model('/content/drive/MyDrive/ml-projects/lung-cancer-detection/Trained Model/model_version3.hdf5')

img_path = "/content/drive/MyDrive/Data/test/adenocarcinoma/000109 (2).png"
image_shape = (305,430,3)
N_CLASSES = 4
BATCH_SIZE = 32
test_path="/content/drive/MyDrive/Data/test"
test_datagen = ImageDataGenerator(dtype='float32', rescale = 1.0/255.0)
test_generator = test_datagen.flow_from_directory(test_path,
                                                   batch_size = BATCH_SIZE,
                                                   target_size = (305,430),
                                                   class_mode = 'categorical')
class_names=list(test_generator.class_indices.keys())
img = load_img(img_path, target_size=(460, 460))
img_array = img_to_array(img)
img_array = np.expand_dims(img_array, 0)

prediction = model.predict(img_array)
imgplot = plt.imshow(img)
plt.show()
print(
    "This image most likely belongs to {} with a {:.2f} percent confidence."
    .format(class_names[np.argmax(prediction)], 100 * np.max(prediction))
)